[workspace]
members = [
    "app", 
    "core",
    "guess",
    "hello-rust",
    "tkio",
    "grpc",
    "guessing_game",
    "my-redis"
]
resolver = "2"

[workspace.package]
name = "learn-rust"
version = "0.0.0"
edition = "2021"

